<?xml version="1.0" encoding="UTF-8"?>
<data version="1.0">
    <struct type="Settings">
        <key>fileFormatVersion</key>
        <int>1</int>
        <key>variation</key>
        <string>main</string>
        <key>verbose</key>
        <false/>
        <key>autoSDSettings</key>
        <array/>
        <key>allowRotation</key>
        <false/>
        <key>quiet</key>
        <false/>
        <key>premultiplyAlpha</key>
        <false/>
        <key>shapeDebug</key>
        <false/>
        <key>dpi</key>
        <uint>72</uint>
        <key>dataFormat</key>
        <string>sparrow</string>
        <key>textureFileName</key>
        <filename>EnemiesAnimated.png</filename>
        <key>flipPVR</key>
        <false/>
        <key>ditherType</key>
        <enum type="SettingsBase::DitherType">NearestNeighbour</enum>
        <key>backgroundColor</key>
        <uint>0</uint>
        <key>libGdx</key>
        <struct type="LibGDX">
            <key>filtering</key>
            <struct type="LibGDXFiltering">
                <key>x</key>
                <enum type="LibGDXFiltering::Filtering">Linear</enum>
                <key>y</key>
                <enum type="LibGDXFiltering::Filtering">Linear</enum>
            </struct>
        </struct>
        <key>shapePadding</key>
        <uint>2</uint>
        <key>jpgQuality</key>
        <uint>80</uint>
        <key>pngOptimizationLevel</key>
        <uint>0</uint>
        <key>textureSubPath</key>
        <string></string>
        <key>textureFormat</key>
        <enum type="SettingsBase::TextureFormat">png</enum>
        <key>borderPadding</key>
        <uint>2</uint>
        <key>maxTextureSize</key>
        <QSize>
            <key>width</key>
            <int>2048</int>
            <key>height</key>
            <int>2048</int>
        </QSize>
        <key>fixedTextureSize</key>
        <QSize>
            <key>width</key>
            <int>-1</int>
            <key>height</key>
            <int>-1</int>
        </QSize>
        <key>reduceBorderArtifacts</key>
        <false/>
        <key>algorithmSettings</key>
        <struct type="AlgorithmSettings">
            <key>algorithm</key>
            <enum type="AlgorithmSettings::AlgorithmId">MaxRects</enum>
            <key>freeSizeMode</key>
            <enum type="AlgorithmSettings::AlgorithmFreeSizeMode">Best</enum>
            <key>sizeConstraints</key>
            <enum type="AlgorithmSettings::SizeConstraints">POT</enum>
            <key>forceSquared</key>
            <false/>
            <key>forceWordAligned</key>
            <false/>
            <key>maxRects</key>
            <struct type="AlgorithmMaxRectsSettings">
                <key>heuristic</key>
                <enum type="AlgorithmMaxRectsSettings::Heuristic">Best</enum>
            </struct>
            <key>basic</key>
            <struct type="AlgorithmBasicSettings">
                <key>sortBy</key>
                <enum type="AlgorithmBasicSettings::SortBy">Best</enum>
                <key>order</key>
                <enum type="AlgorithmBasicSettings::Order">Ascending</enum>
            </struct>
        </struct>
        <key>andEngine</key>
        <struct type="AndEngine">
            <key>minFilter</key>
            <enum type="AndEngine::MinFilter">Linear</enum>
            <key>packageName</key>
            <string>Texture</string>
            <key>javaFileName</key>
            <filename>EnemiesAnimated.java</filename>
            <key>wrap</key>
            <struct type="AndEngineWrap">
                <key>s</key>
                <enum type="AndEngineWrap::Wrap">Clamp</enum>
                <key>t</key>
                <enum type="AndEngineWrap::Wrap">Clamp</enum>
            </struct>
            <key>magFilter</key>
            <enum type="AndEngine::MagFilter">MagLinear</enum>
        </struct>
        <key>dataFileName</key>
        <filename>EnemiesAnimated.xml</filename>
        <key>mainExtension</key>
        <string></string>
        <key>forceIdenticalLayout</key>
        <false/>
        <key>outputFormat</key>
        <enum type="SettingsBase::OutputFormat">RGBA8888</enum>
        <key>contentProtection</key>
        <struct type="ContentProtection">
            <key>key</key>
            <string></string>
        </struct>
        <key>autoAliasEnabled</key>
        <true/>
        <key>trimSpriteNames</key>
        <false/>
        <key>globalSpriteSettings</key>
        <struct type="SpriteSettings">
            <key>scale</key>
            <double>1</double>
            <key>scaleMode</key>
            <enum type="ScaleMode">Smooth</enum>
            <key>innerPadding</key>
            <uint>0</uint>
            <key>extrude</key>
            <uint>0</uint>
            <key>trimThreshold</key>
            <uint>1</uint>
            <key>trimMode</key>
            <enum type="SpriteSettings::TrimMode">Trim</enum>
            <key>heuristicMask</key>
            <false/>
        </struct>
        <key>fileList</key>
        <array>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10001.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10002.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10003.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10004.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10005.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10006.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10007.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10008.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10009.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10010.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10011.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10012.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10013.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10014.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10015.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10016.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10017.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10018.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10019.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10020.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10021.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10022.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10023.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10024.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10025.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10026.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10027.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10028.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10029.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10030.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10031.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10032.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10033.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10034.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10035.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10036.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10037.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10038.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10039.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10040.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10041.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10042.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10043.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10044.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10045.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10046.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10047.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10048.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10049.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10050.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10051.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10052.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10053.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10054.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10055.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10056.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10057.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10058.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10059.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy10060.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20001.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20002.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20003.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20004.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20005.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20006.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20007.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20008.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20009.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20010.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20011.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20012.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20013.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20014.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20015.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20016.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20017.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20018.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20019.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20020.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20021.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20022.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20023.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20024.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20025.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20026.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20027.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20028.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20029.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20030.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20031.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20032.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20033.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20034.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20035.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20036.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20037.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20038.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20039.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20040.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20041.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20042.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20043.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20044.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20045.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20046.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20047.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20048.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20049.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20050.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20051.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20052.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20053.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20054.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20055.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20056.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20057.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20058.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20059.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy20060.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30001.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30002.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30003.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30004.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30005.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30006.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30007.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30008.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30009.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30010.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30011.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30012.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30013.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30014.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30015.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30016.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30017.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30018.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30019.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30020.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30021.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30022.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30023.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30024.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30025.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30026.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30027.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30028.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30029.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30030.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30031.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30032.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30033.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30034.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30035.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30036.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30037.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30038.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30039.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30040.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30041.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30042.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30043.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30044.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30045.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30046.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30047.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30048.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30049.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30050.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30051.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30052.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30053.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30054.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30055.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30056.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30057.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30058.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30059.png</filename>
            <filename>../../../../../../../../../Desktop/allparticles/enemy30060.png</filename>
        </array>
        <key>ignoreFileList</key>
        <array/>
        <key>replaceList</key>
        <array/>
        <key>ignoredWarnings</key>
        <array/>
        <key>commonDivisorX</key>
        <uint>1</uint>
        <key>commonDivisorY</key>
        <uint>1</uint>
    </struct>
</data>
